
import React from 'react';
import { Sun, SunDim, CloudMoon, Moon, Zap, Target, Layers, Heart } from 'lucide-react';
import { TimePeriod, TimeBlockConfig, TaskWeight } from './types';

export const WEIGHT_CONFIG = {
  [TaskWeight.quick]: { label: 'Quick', points: 1, icon: Zap, color: 'var(--flow-weight-quick-color)' },
  [TaskWeight.focused]: { label: 'Focused', points: 3, icon: Target, color: 'var(--flow-weight-focused-color)' },
  [TaskWeight.deep]: { label: 'Deep', points: 6, icon: Layers, color: 'var(--flow-weight-deep-color)' }
};

export const RECOVERY_TIPS = {
  en: [
    "A 48-hour disconnect increases your creativity by 60% for the week ahead.",
    "Cognitive performance drops by 25% after 6 days of continuous work without a full day off.",
    "Active rest, like walking in nature, accelerates neural recovery more than passive rest.",
    "Your brain consolidates complex problem-solving strategies during periods of 'Free Flow' leisure.",
    "Recovery isn't just absence of work; it's the presence of restorative activities."
  ],
  ru: [
    "48-часовое отключение повышает вашу креативность на 60% на предстоящую неделю.",
    "Когнитивные показатели падают на 25% после 6 дней непрерывной работы без полноценного выходного.",
    "Активный отдых, например, прогулка на природе, ускоряет восстановление нейронов эффективнее пассивного отдыха.",
    "Ваш мозг закрепляет стратегии решения сложных задач в периоды свободного досуга.",
    "Восстановление — это не просто отсутствие работы, это наличие восстанавливающих занятий."
  ],
  es: [
    "Desconectarse por 48 horas aumenta tu creatividad en un 60% para la semana siguiente.",
    "El rendimiento cognitivo cae un 25% después de 6 días de trabajo continuo sin un día libre.",
    "El descanso activo, como caminar en la naturaleza, acelera la recuperación neural más que el descanso pasivo.",
    "Tu cerebro consolida estrategias complejas de resolución de problemas durante los periodos de ocio 'Free Flow'.",
    "Recuperación no es solo ausencia de trabajo; es la presencia de actividades reparadoras."
  ]
};

export const ALARM_SOUNDS = [
  { id: 'forest', label: { en: 'Forest', ru: 'Лес', es: 'Bosque' }, url: 'https://assets.mixkit.co/active_storage/sfx/2432/2432-preview.mp3' },
  { id: 'sea', label: { en: 'Sea Waves', ru: 'Морские волны', es: 'Olas del mar' }, url: 'https://assets.mixkit.co/active_storage/sfx/1110/1110-preview.mp3' },
  { id: 'water', label: { en: 'Stream', ru: 'Ручей', es: 'Arroyo' }, url: 'https://assets.mixkit.co/active_storage/sfx/1114/1114-preview.mp3' },
  { id: 'birds', label: { en: 'Morning Birds', ru: 'Утренние птицы', es: 'Pájaros matutinos' }, url: 'https://assets.mixkit.co/active_storage/sfx/2431/2431-preview.mp3' },
  { id: 'rain', label: { en: 'Soft Rain', ru: 'Тихий дождь', es: 'Lluvia suave' }, url: 'https://assets.mixkit.co/active_storage/sfx/1112/1112-preview.mp3' },
  { id: 'wind', label: { en: 'Mountain Wind', ru: 'Горный ветер', es: 'Viento de montaña' }, url: 'https://assets.mixkit.co/active_storage/sfx/1116/1116-preview.mp3' },
  { id: 'zen', label: { en: 'Zen Bowl', ru: 'Дзен-чаша', es: 'Cuenco Zen' }, url: 'https://assets.mixkit.co/active_storage/sfx/1118/1118-preview.mp3' },
];

export const TRANSLATIONS = {
  en: {
    today: "Today's Flow",
    day: "Day",
    upcoming: "Future Flow",
    week: "Week",
    month: "Month",
    year: "Year",
    prev: "Previous",
    next: "Next",
    rhythm: "Your Rhythm",
    alarm: "Alarm Clock",
    settings: "Settings",
    now: "Now",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    goodNight: "Good Night",
    recoveryMode: "Recovery Mode",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    night: "Night",
    addPoint: "Focus Point",
    placeholder: "What are we doing next?",
    addButton: "Add to Flow",
    weightless: "Weightless",
    leisure: "Pure leisure only.",
    recoveryActive: "Neural Recovery Active",
    save: "Save Changes",
    language: "Language",
    sound: "Wake-up Sound",
    enableAlarm: "Enable Alarm",
    moveTask: "Move to",
    carriedForward: "Carried Forward",
    syncCalendar: "Sync to Calendar",
    deadline: "No Deadline",
    noUpcoming: "No upcoming tasks scheduled.",
    upcomingTasks: "Upcoming Tasks",
    flowStart: "Good morning. Your flow starts now.",
    enterThread: "Enter Thread",
    snooze: "5 more minutes",
    recurrence: "Repeat",
    rec_none: "Once",
    rec_daily: "Every Day",
    rec_weekly: "Every Week",
    rec_monthly: "Every Month",
    rec_all_blocks: "3x / Day",
    taskTransferred: 'Task "{title}" transferred to {period}',
    taskTransferredTomorrow: 'Task "{title}" transferred to {period} tomorrow ({date})',
    allBlocksFull: "All blocks are full! Task added with exceeded limit.",
    blockOverflow: "(block overflow)",
    sleepGapError: "Sleep gap must be at least 7 hours."
  },
  ru: {
    today: "Ваш поток",
    day: "День",
    upcoming: "Будущий поток",
    week: "Неделя",
    month: "Месяц",
    year: "Год",
    prev: "Назад",
    next: "Вперед",
    rhythm: "Ваш ритм",
    alarm: "Будильник",
    settings: "Настройки",
    now: "Сейчас",
    goodMorning: "Доброе утро",
    goodAfternoon: "Добрый день",
    goodEvening: "Добрый вечер",
    goodNight: "Доброй ночи",
    recoveryMode: "Режим восстановления",
    morning: "Утро",
    afternoon: "День",
    evening: "Вечер",
    night: "Ночь",
    addPoint: "Точка фокуса",
    placeholder: "Что планируем дальше?",
    addButton: "В поток",
    weightless: "Налегке",
    leisure: "Только отдых.",
    recoveryActive: "Восстановление нейронов",
    save: "Сохранить",
    language: "Язык",
    sound: "Звук пробуждения",
    enableAlarm: "Включить будильник",
    moveTask: "Переместить в",
    carriedForward: "Перенесено",
    syncCalendar: "В календарь",
    deadline: "Без дедлайна",
    noUpcoming: "Будущих задач не запланировано.",
    upcomingTasks: "Предстоящие задачи",
    flowStart: "Доброе утро. Ваш поток начинается сейчас.",
    enterThread: "Войти в поток",
    snooze: "Еще 5 минут",
    recurrence: "Повтор",
    rec_none: "Один раз",
    rec_daily: "Ежедневно",
    rec_weekly: "Еженедельно",
    rec_monthly: "Ежемесячно",
    rec_all_blocks: "3 раза в день",
    taskTransferred: 'Задача "{title}" перенесена на {period}',
    taskTransferredTomorrow: 'Задача "{title}" перенесена на {period} завтра ({date})',
    allBlocksFull: "Все блоки переполнены! Задача добавлена с превышением лимита.",
    blockOverflow: "(блок переполнен)",
    sleepGapError: "Сон должен длиться не менее 7 часов."
  },
  es: {
    today: "Tu Flujo",
    day: "Día",
    upcoming: "Flujo Futuro",
    week: "Semana",
    month: "Mes",
    year: "Año",
    prev: "Anterior",
    next: "Siguiente",
    rhythm: "Tu Ritmo",
    alarm: "Reloj Alarma",
    settings: "Ajustes",
    now: "Ahora",
    goodMorning: "Buenos Días",
    goodAfternoon: "Buenas Tardes",
    goodEvening: "Buenas Noches",
    goodNight: "Buenas Noches",
    recoveryMode: "Modo Recuperación",
    morning: "Mañana",
    afternoon: "Tarde",
    evening: "Noche",
    night: "Noche",
    addPoint: "Punto de Enfoque",
    placeholder: "¿Qué haremos después?",
    addButton: "Añadir al Flujo",
    weightless: "Ligero",
    leisure: "Puro ocio solamente.",
    recoveryActive: "Recuperación Neural Activa",
    save: "Guardar Cambios",
    language: "Idioma",
    sound: "Sonido Despertar",
    enableAlarm: "Activar Alarma",
    moveTask: "Mover a",
    carriedForward: "Continuado",
    syncCalendar: "Sincronizar Calendario",
    deadline: "Sin Fecha Límite",
    noUpcoming: "No hay tareas programadas.",
    upcomingTasks: "Tareas Próximas",
    flowStart: "Buenos días. Tu flujo comienza ahora.",
    enterThread: "Entrar al Flujo",
    snooze: "5 minutos más",
    recurrence: "Repetir",
    rec_none: "Una vez",
    rec_daily: "Diario",
    rec_weekly: "Semanal",
    rec_monthly: "Mensual",
    rec_all_blocks: "3x / Día",
    taskTransferred: 'Tarea "{title}" transferida a {period}',
    taskTransferredTomorrow: 'Tarea "{title}" transferida a {period} mañana ({date})',
    allBlocksFull: "¡Todos los bloques están llenos! Tarea añadida con límite excedido.",
    blockOverflow: "(bloque desbordado)",
    sleepGapError: "El período de sueño debe ser de al menos 7 horas."
  }
};

export const VOICE_TRANSLATIONS = {
  en: {
    listening: 'Listening...',
    processing: 'Processing...',
    error: 'Sorry, I didn\'t catch that',
    confirmAdd: 'Add task "{title}"?',
    confirmDelete: 'Delete this task?',
    confirmToggle: 'Mark task as completed?',
    taskAdded: 'Task added',
    taskDeleted: 'Task deleted',
    taskCompleted: 'Task completed',
    taskUpdated: 'Task updated',
    navigated: 'Done',
    viewChanged: 'View changed',
    noMicrophone: 'Microphone not available',
    permissionDenied: 'Microphone permission denied',
    voiceSettings: 'Voice Control',
    enableVoice: 'Enable Voice Control',
    voiceLanguage: 'Voice Language',
    autoSubmit: 'Auto Submit Commands',
    requireConfirmation: 'Require Confirmation',
    enableTTS: 'Voice Feedback',
    confidenceThreshold: 'Recognition Confidence',
    russian: 'Russian',
    english: 'English',
    spanish: 'Spanish'
  },
  ru: {
    listening: 'Слушаю...',
    processing: 'Обработка...',
    error: 'Извините, я не понял',
    confirmAdd: 'Добавить задачу "{title}"?',
    confirmDelete: 'Удалить эту задачу?',
    confirmToggle: 'Отметить задачу выполненной?',
    taskAdded: 'Задача добавлена',
    taskDeleted: 'Задача удалена',
    taskCompleted: 'Задача выполнена',
    taskUpdated: 'Задача обновлена',
    navigated: 'Готово',
    viewChanged: 'Вид изменен',
    noMicrophone: 'Микрофон недоступен',
    permissionDenied: 'Доступ к микрофону запрещен',
    voiceSettings: 'Голосовое управление',
    enableVoice: 'Включить голосовое управление',
    voiceLanguage: 'Язык голоса',
    autoSubmit: 'Автоматическая отправка',
    requireConfirmation: 'Требовать подтверждение',
    enableTTS: 'Голосовая обратная связь',
    confidenceThreshold: 'Уверенность распознавания',
    russian: 'Русский',
    english: 'Английский',
    spanish: 'Испанский'
  },
  es: {
    listening: 'Escuchando...',
    processing: 'Procesando...',
    error: 'Lo siento, no entendí',
    confirmAdd: '¿Añadir tarea "{title}"?',
    confirmDelete: '¿Eliminar esta tarea?',
    confirmToggle: '¿Marcar tarea como completada?',
    taskAdded: 'Tarea añadida',
    taskDeleted: 'Tarea eliminada',
    taskCompleted: 'Tarea completada',
    taskUpdated: 'Tarea actualizada',
    navigated: 'Hecho',
    viewChanged: 'Vista cambiada',
    noMicrophone: 'Micrófono no disponible',
    permissionDenied: 'Permiso de micrófono denegado',
    voiceSettings: 'Control por voz',
    enableVoice: 'Activar control por voz',
    voiceLanguage: 'Idioma de voz',
    autoSubmit: 'Envío automático de comandos',
    requireConfirmation: 'Requerir confirmación',
    enableTTS: 'Comentarios de voz',
    confidenceThreshold: 'Confianza de reconocimiento',
    russian: 'Ruso',
    english: 'Inglés',
    spanish: 'Español'
  }
};

export const BLOCK_CAPACITY = 12;

export const getIcon = (iconName: string, className?: string, size: number = 24) => {
  switch (iconName) {
    case 'Sun': return <Sun size={size} className={className} />;
    case 'SunDim': return <SunDim size={size} className={className} />;
    case 'CloudMoon': return <CloudMoon size={size} className={className} />;
    case 'Moon': return <Moon size={size} className={className} />;
    case 'Heart': return <Heart size={size} className={className} />;
    default: return null;
  }
};
